package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

// emitMigration writes rows as a golang-migrate .up.sql file, so a run
// intended to be permanent survives a db/init.sql regeneration -- the
// on-disk fate of the container's Postgres data otherwise. It renders the
// exact same rows writeRows already upserted; there is deliberately no
// second query builder for this path.
func emitMigration(path string, rows []descriptionRow) error {
	if len(rows) == 0 {
		return fmt.Errorf("no rows to emit")
	}

	byEntity := map[entity][]descriptionRow{}
	for _, r := range rows {
		byEntity[r.Entity] = append(byEntity[r.Entity], r)
	}
	for _, rs := range byEntity {
		sort.Slice(rs, func(i, j int) bool {
			if rs[i].ID != rs[j].ID {
				return rs[i].ID < rs[j].ID
			}
			return rs[i].Version < rs[j].Version
		})
	}

	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by cmd/scrape on %s.\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "-- %d rows: %s\n", len(rows), sourceSummary(rows))
	fmt.Fprintf(&b, "--\n")
	fmt.Fprintf(&b, "-- Gap-fill only: DO NOTHING on an existing (id, version) row, so applying\n")
	fmt.Fprintf(&b, "-- this migration never overwrites text this database already had.\n\n")
	fmt.Fprintf(&b, "BEGIN;\n\n")

	writeInsertBlock(&b, byEntity[entityPokemon], "public.pokemondescriptions", "pokemon_id")
	writeInsertBlock(&b, byEntity[entityMove], "public.movedescriptions", "move_id")
	writeInsertBlock(&b, byEntity[entityAbility], "public.abilitydescriptions", "ability_id")

	fmt.Fprintf(&b, "COMMIT;\n")

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return err
	}

	downPath := strings.TrimSuffix(path, ".up.sql") + ".down.sql"
	return os.WriteFile(downPath, []byte(downMigration(byEntity)), 0o644)
}

func writeInsertBlock(b *strings.Builder, rows []descriptionRow, table, idCol string) {
	if len(rows) == 0 {
		return
	}
	fmt.Fprintf(b, "INSERT INTO %s (%s, version, text) VALUES\n", table, idCol)
	for i, r := range rows {
		sep := ","
		if i == len(rows)-1 {
			sep = ""
		}
		fmt.Fprintf(b, "    (%d, %s, %s)%s\n", r.ID, sqlString(r.Version), sqlString(r.Text), sep)
	}
	fmt.Fprintf(b, "ON CONFLICT (%s, version) DO NOTHING;\n\n", idCol)
}

func sqlString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func sourceSummary(rows []descriptionRow) string {
	counts := map[string]int{}
	for _, r := range rows {
		counts[r.Source]++
	}
	var parts []string
	for _, src := range []string{"pokeapi", "bulbapedia"} {
		if n, ok := counts[src]; ok {
			parts = append(parts, src+"="+strconv.Itoa(n))
		}
	}
	return strings.Join(parts, ", ")
}

// downMigration deletes exactly the (id, version) pairs the up migration
// added, scoped by the ids and versions actually present in this run so it
// never touches a row a different source or a later run wrote.
func downMigration(byEntity map[entity][]descriptionRow) string {
	var b strings.Builder
	b.WriteString("-- Reverse of the paired .up.sql: deletes only the exact\n")
	b.WriteString("-- (id, version) pairs that migration inserted.\n\n")
	b.WriteString("BEGIN;\n\n")

	del := func(rows []descriptionRow, table, idCol string) {
		if len(rows) == 0 {
			return
		}
		fmt.Fprintf(&b, "DELETE FROM %s WHERE (%s, version) IN (\n", table, idCol)
		for i, r := range rows {
			sep := ","
			if i == len(rows)-1 {
				sep = ""
			}
			fmt.Fprintf(&b, "    (%d, %s)%s\n", r.ID, sqlString(r.Version), sep)
		}
		b.WriteString(");\n\n")
	}
	del(byEntity[entityPokemon], "public.pokemondescriptions", "pokemon_id")
	del(byEntity[entityMove], "public.movedescriptions", "move_id")
	del(byEntity[entityAbility], "public.abilitydescriptions", "ability_id")

	b.WriteString("COMMIT;\n")
	return b.String()
}

// emitEggMoveMigration is emitMigration's movedetails counterpart. It can't
// reuse writeInsertBlock/downMigration above: movedetails has no unique
// constraint (see insertEggMove in queries.go), so the generated SQL needs
// a WHERE NOT EXISTS guard per row instead of ON CONFLICT, and the row
// shape itself differs (method/level_learned, no text column).
func emitEggMoveMigration(path string, rows []moveDetailRow) error {
	if len(rows) == 0 {
		return fmt.Errorf("no rows to emit")
	}

	sorted := make([]moveDetailRow, len(rows))
	copy(sorted, rows)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].PokemonID != sorted[j].PokemonID {
			return sorted[i].PokemonID < sorted[j].PokemonID
		}
		if sorted[i].MoveID != sorted[j].MoveID {
			return sorted[i].MoveID < sorted[j].MoveID
		}
		return sorted[i].Version < sorted[j].Version
	})

	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by cmd/scrape -only=eggmoves on %s.\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "-- %d egg-move rows from Bulbapedia's \"By breeding\" sections.\n", len(sorted))
	fmt.Fprintf(&b, "--\n")
	fmt.Fprintf(&b, "-- Gap-fill only: movedetails has no unique constraint (8,575 pre-existing\n")
	fmt.Fprintf(&b, "-- level-up duplicates are legitimate game data -- the same move learned at\n")
	fmt.Fprintf(&b, "-- two different levels), so each INSERT is individually guarded with\n")
	fmt.Fprintf(&b, "-- WHERE NOT EXISTS rather than ON CONFLICT, matching cmd/scrape's own\n")
	fmt.Fprintf(&b, "-- insertEggMove query. Applying this migration never overwrites or\n")
	fmt.Fprintf(&b, "-- deletes an existing egg-move row.\n\n")
	fmt.Fprintf(&b, "BEGIN;\n\n")

	for _, r := range sorted {
		fmt.Fprintf(&b, "INSERT INTO public.movedetails (pokemon_id, move_id, method, level_learned, version)\n")
		fmt.Fprintf(&b, "SELECT %d, %d, 'egg', 0, %s\n", r.PokemonID, r.MoveID, sqlString(r.Version))
		fmt.Fprintf(&b, "WHERE NOT EXISTS (SELECT 1 FROM public.movedetails\n")
		fmt.Fprintf(&b, "  WHERE pokemon_id=%d AND move_id=%d AND method='egg' AND version=%s);\n\n",
			r.PokemonID, r.MoveID, sqlString(r.Version))
	}

	fmt.Fprintf(&b, "COMMIT;\n")

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return err
	}

	downPath := strings.TrimSuffix(path, ".up.sql") + ".down.sql"
	return os.WriteFile(downPath, []byte(downEggMoveMigration(sorted)), 0o644)
}

// downEggMoveMigration deletes exactly the (pokemon_id, move_id, version)
// triples the up migration added, scoped to method='egg' so it can never
// touch a level-up/tutor/machine row even if one happens to share the same
// (pokemon_id, move_id, version) tuple.
func downEggMoveMigration(rows []moveDetailRow) string {
	var b strings.Builder
	b.WriteString("-- Reverse of the paired .up.sql: deletes only the exact\n")
	b.WriteString("-- (pokemon_id, move_id, version) egg-move rows that migration inserted.\n\n")
	b.WriteString("BEGIN;\n\n")

	if len(rows) > 0 {
		b.WriteString("DELETE FROM public.movedetails WHERE method='egg' AND (pokemon_id, move_id, version) IN (\n")
		for i, r := range rows {
			sep := ","
			if i == len(rows)-1 {
				sep = ""
			}
			fmt.Fprintf(&b, "    (%d, %d, %s)%s\n", r.PokemonID, r.MoveID, sqlString(r.Version), sep)
		}
		b.WriteString(");\n\n")
	}

	b.WriteString("COMMIT;\n")
	return b.String()
}

// sqlNullableInt renders a *int32 as a SQL literal: NULL for a nil pointer,
// the plain decimal value otherwise. Every legendsmovevalues column besides
// the primary key is nullable -- Legends: Z-A rows leave power_strong/
// power_agile/accuracy_2/pp NULL and populate cooldown; Legends: Arceus
// rows do the reverse -- so this is used for all eight of them.
func sqlNullableInt(v *int32) string {
	if v == nil {
		return "NULL"
	}
	return strconv.Itoa(int(*v))
}

// emitLegendsMigration is emitEggMoveMigration's Legends: Arceus/Z-A
// counterpart. It writes two kinds of statement: one guarded movedetails
// INSERT per row (same WHERE NOT EXISTS reasoning as insertLegendsMove),
// and a single multi-row legendsmovevalues INSERT covering the deduplicated
// (pokemon_id, move_id, version) keys -- deduplicated here because a move
// learnable two ways in one game (see writeLegendsMoveRows) would otherwise
// appear twice in the VALUES list for the same primary key; ON CONFLICT DO
// NOTHING would tolerate that at apply time too, but emitting one row is
// clearer to read.
func emitLegendsMigration(path string, rows []legendsMoveRow) error {
	if len(rows) == 0 {
		return fmt.Errorf("no rows to emit")
	}

	sorted := make([]legendsMoveRow, len(rows))
	copy(sorted, rows)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].PokemonID != sorted[j].PokemonID {
			return sorted[i].PokemonID < sorted[j].PokemonID
		}
		if sorted[i].MoveID != sorted[j].MoveID {
			return sorted[i].MoveID < sorted[j].MoveID
		}
		if sorted[i].Version != sorted[j].Version {
			return sorted[i].Version < sorted[j].Version
		}
		return sorted[i].Method < sorted[j].Method
	})

	type valuesKey struct {
		pid, mid int32
		ver      string
	}
	seen := map[valuesKey]bool{}
	var valueRows []legendsMoveRow
	for _, r := range sorted {
		k := valuesKey{r.PokemonID, r.MoveID, r.Version}
		if seen[k] {
			continue
		}
		seen[k] = true
		valueRows = append(valueRows, r)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by cmd/scrape -only=legends on %s.\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "-- %d movedetails rows, %d legendsmovevalues rows, from Bulbapedia's\n", len(sorted), len(valueRows))
	fmt.Fprintf(&b, "-- Legends: Arceus / Legends: Z-A learnset entries.\n")
	fmt.Fprintf(&b, "--\n")
	fmt.Fprintf(&b, "-- Gap-fill only, same as 000009's egg moves: movedetails inserts are each\n")
	fmt.Fprintf(&b, "-- individually WHERE NOT EXISTS-guarded (no unique constraint on that\n")
	fmt.Fprintf(&b, "-- table); legendsmovevalues rows are deduplicated here on its real PK\n")
	fmt.Fprintf(&b, "-- (pokemon_id, move_id, version) -- a move learnable both by level-up and\n")
	fmt.Fprintf(&b, "-- tutor/TM in the same game (e.g. Legends: Arceus's Iron Tail for Pikachu)\n")
	fmt.Fprintf(&b, "-- has identical stats regardless of learn method, so one row serves every\n")
	fmt.Fprintf(&b, "-- movedetails row for that (pokemon, move, version) triple -- and ON\n")
	fmt.Fprintf(&b, "-- CONFLICT DO NOTHING backs that up at apply time too.\n\n")
	fmt.Fprintf(&b, "BEGIN;\n\n")

	for _, r := range sorted {
		fmt.Fprintf(&b, "INSERT INTO public.movedetails (pokemon_id, move_id, method, level_learned, version)\n")
		fmt.Fprintf(&b, "SELECT %d, %d, %s, %d, %s\n", r.PokemonID, r.MoveID, sqlString(r.Method), r.Level, sqlString(r.Version))
		fmt.Fprintf(&b, "WHERE NOT EXISTS (SELECT 1 FROM public.movedetails\n")
		fmt.Fprintf(&b, "  WHERE pokemon_id=%d AND move_id=%d AND method=%s AND level_learned=%d AND version=%s);\n\n",
			r.PokemonID, r.MoveID, sqlString(r.Method), r.Level, sqlString(r.Version))
	}

	fmt.Fprintf(&b, "INSERT INTO public.legendsmovevalues\n")
	fmt.Fprintf(&b, "  (pokemon_id, move_id, version, second_level, power_base, power_strong, power_agile, accuracy_1, accuracy_2, pp, cooldown)\n")
	fmt.Fprintf(&b, "VALUES\n")
	for i, r := range valueRows {
		sep := ","
		if i == len(valueRows)-1 {
			sep = ""
		}
		fmt.Fprintf(&b, "    (%d, %d, %s, %s, %s, %s, %s, %s, %s, %s, %s)%s\n",
			r.PokemonID, r.MoveID, sqlString(r.Version),
			sqlNullableInt(r.SecondLevel), sqlNullableInt(r.PowerBase), sqlNullableInt(r.PowerStrong), sqlNullableInt(r.PowerAgile),
			sqlNullableInt(r.Accuracy1), sqlNullableInt(r.Accuracy2), sqlNullableInt(r.PP), sqlNullableInt(r.Cooldown), sep)
	}
	fmt.Fprintf(&b, "ON CONFLICT (pokemon_id, move_id, version) DO NOTHING;\n\n")

	fmt.Fprintf(&b, "COMMIT;\n")

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return err
	}

	downPath := strings.TrimSuffix(path, ".up.sql") + ".down.sql"
	return os.WriteFile(downPath, []byte(downLegendsMigration(sorted, valueRows)), 0o644)
}

// downLegendsMigration deletes exactly the movedetails and legendsmovevalues
// rows the up migration added, scoped by their full keys (including method
// and level_learned for movedetails) so it can never touch an unrelated row
// that happens to share part of the key.
func downLegendsMigration(rows []legendsMoveRow, valueRows []legendsMoveRow) string {
	var b strings.Builder
	b.WriteString("-- Reverse of the paired .up.sql: deletes only the exact\n")
	b.WriteString("-- (pokemon_id, move_id, method, level_learned, version) movedetails rows\n")
	b.WriteString("-- and (pokemon_id, move_id, version) legendsmovevalues rows that migration\n")
	b.WriteString("-- inserted.\n\n")
	b.WriteString("BEGIN;\n\n")

	if len(rows) > 0 {
		b.WriteString("DELETE FROM public.movedetails WHERE (pokemon_id, move_id, method, level_learned, version) IN (\n")
		for i, r := range rows {
			sep := ","
			if i == len(rows)-1 {
				sep = ""
			}
			fmt.Fprintf(&b, "    (%d, %d, %s, %d, %s)%s\n", r.PokemonID, r.MoveID, sqlString(r.Method), r.Level, sqlString(r.Version), sep)
		}
		b.WriteString(");\n\n")
	}
	if len(valueRows) > 0 {
		b.WriteString("DELETE FROM public.legendsmovevalues WHERE (pokemon_id, move_id, version) IN (\n")
		for i, r := range valueRows {
			sep := ","
			if i == len(valueRows)-1 {
				sep = ""
			}
			fmt.Fprintf(&b, "    (%d, %d, %s)%s\n", r.PokemonID, r.MoveID, sqlString(r.Version), sep)
		}
		b.WriteString(");\n\n")
	}

	b.WriteString("COMMIT;\n")
	return b.String()
}
