package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

// emitMigration writes rows as a golang-migrate .up.sql file, so a run
// intended to be permanent survives a db/init.sql regeneration -- the
// on-disk fate of the container's Postgres data otherwise. It renders the
// exact same rows writeRows already upserted; there is deliberately no
// second query builder for this path.
func emitMigration(path string, rows []descriptionRow) error {
	if len(rows) == 0 {
		return fmt.Errorf("no rows to emit")
	}

	byEntity := map[entity][]descriptionRow{}
	for _, r := range rows {
		byEntity[r.Entity] = append(byEntity[r.Entity], r)
	}
	for _, rs := range byEntity {
		sort.Slice(rs, func(i, j int) bool {
			if rs[i].ID != rs[j].ID {
				return rs[i].ID < rs[j].ID
			}
			return rs[i].Version < rs[j].Version
		})
	}

	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by cmd/scrape on %s.\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "-- %d rows: %s\n", len(rows), sourceSummary(rows))
	fmt.Fprintf(&b, "--\n")
	fmt.Fprintf(&b, "-- Gap-fill only: DO NOTHING on an existing (id, version) row, so applying\n")
	fmt.Fprintf(&b, "-- this migration never overwrites text this database already had.\n\n")
	fmt.Fprintf(&b, "BEGIN;\n\n")

	writeInsertBlock(&b, byEntity[entityPokemon], "public.pokemondescriptions", "pokemon_id")
	writeInsertBlock(&b, byEntity[entityMove], "public.movedescriptions", "move_id")
	writeInsertBlock(&b, byEntity[entityAbility], "public.abilitydescriptions", "ability_id")

	fmt.Fprintf(&b, "COMMIT;\n")

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return err
	}

	downPath := strings.TrimSuffix(path, ".up.sql") + ".down.sql"
	return os.WriteFile(downPath, []byte(downMigration(byEntity)), 0o644)
}

func writeInsertBlock(b *strings.Builder, rows []descriptionRow, table, idCol string) {
	if len(rows) == 0 {
		return
	}
	fmt.Fprintf(b, "INSERT INTO %s (%s, version, text) VALUES\n", table, idCol)
	for i, r := range rows {
		sep := ","
		if i == len(rows)-1 {
			sep = ""
		}
		fmt.Fprintf(b, "    (%d, %s, %s)%s\n", r.ID, sqlString(r.Version), sqlString(r.Text), sep)
	}
	fmt.Fprintf(b, "ON CONFLICT (%s, version) DO NOTHING;\n\n", idCol)
}

func sqlString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func sourceSummary(rows []descriptionRow) string {
	counts := map[string]int{}
	for _, r := range rows {
		counts[r.Source]++
	}
	var parts []string
	for _, src := range []string{"pokeapi", "bulbapedia"} {
		if n, ok := counts[src]; ok {
			parts = append(parts, src+"="+strconv.Itoa(n))
		}
	}
	return strings.Join(parts, ", ")
}

// downMigration deletes exactly the (id, version) pairs the up migration
// added, scoped by the ids and versions actually present in this run so it
// never touches a row a different source or a later run wrote.
func downMigration(byEntity map[entity][]descriptionRow) string {
	var b strings.Builder
	b.WriteString("-- Reverse of the paired .up.sql: deletes only the exact\n")
	b.WriteString("-- (id, version) pairs that migration inserted.\n\n")
	b.WriteString("BEGIN;\n\n")

	del := func(rows []descriptionRow, table, idCol string) {
		if len(rows) == 0 {
			return
		}
		fmt.Fprintf(&b, "DELETE FROM %s WHERE (%s, version) IN (\n", table, idCol)
		for i, r := range rows {
			sep := ","
			if i == len(rows)-1 {
				sep = ""
			}
			fmt.Fprintf(&b, "    (%d, %s)%s\n", r.ID, sqlString(r.Version), sep)
		}
		b.WriteString(");\n\n")
	}
	del(byEntity[entityPokemon], "public.pokemondescriptions", "pokemon_id")
	del(byEntity[entityMove], "public.movedescriptions", "move_id")
	del(byEntity[entityAbility], "public.abilitydescriptions", "ability_id")

	b.WriteString("COMMIT;\n")
	return b.String()
}
