// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: abilities.sql

package store

import (
	"context"
)

const getAbilitiesList = `-- name: GetAbilitiesList :many
SELECT id, name, gen 
FROM ability 
ORDER BY id, gen ASC
`

type GetAbilitiesListRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Gen  int32  `json:"gen"`
}

func (q *Queries) GetAbilitiesList(ctx context.Context) ([]GetAbilitiesListRow, error) {
	rows, err := q.db.Query(ctx, getAbilitiesList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAbilitiesListRow
	for rows.Next() {
		var i GetAbilitiesListRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Gen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAbility = `-- name: GetAbility :one
SELECT id, name, gen, effect
FROM ability 
WHERE id = $1
`

func (q *Queries) GetAbility(ctx context.Context, id int32) (Ability, error) {
	row := q.db.QueryRow(ctx, getAbility, id)
	var i Ability
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gen,
		&i.Effect,
	)
	return i, err
}

const getAbilityByName = `-- name: GetAbilityByName :one
SELECT id, name, gen, effect
FROM ability 
WHERE name = $1
`

func (q *Queries) GetAbilityByName(ctx context.Context, name string) (Ability, error) {
	row := q.db.QueryRow(ctx, getAbilityByName, name)
	var i Ability
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gen,
		&i.Effect,
	)
	return i, err
}

const getAbilityDescriptions = `-- name: GetAbilityDescriptions :many
SELECT array_agg(version ORDER BY version)::text[] AS games,
       text
FROM abilitydescriptions
WHERE ability_id = $1
GROUP BY text
ORDER BY min(version)
`

type GetAbilityDescriptionsRow struct {
	Games []string `json:"games"`
	Text  string   `json:"text"`
}

// Same grouping as GetPokemonDescriptionsByIDs; see the note there.
func (q *Queries) GetAbilityDescriptions(ctx context.Context, abilityID int32) ([]GetAbilityDescriptionsRow, error) {
	rows, err := q.db.Query(ctx, getAbilityDescriptions, abilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAbilityDescriptionsRow
	for rows.Next() {
		var i GetAbilityDescriptionsRow
		if err := rows.Scan(&i.Games, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPokemonLearnableAbility = `-- name: GetPokemonLearnableAbility :many
SELECT DISTINCT p.id, p.name, p.gen, p.type1, p.type2, p.species_id
FROM abilitydetails
JOIN pokemon p ON p.id = pokemon_id
WHERE ability_id = $1
ORDER BY p.species_id, p.id ASC
`

type GetPokemonLearnableAbilityRow struct {
	ID        int32   `json:"id"`
	Name      string  `json:"name"`
	Gen       int32   `json:"gen"`
	Type1     string  `json:"type1"`
	Type2     *string `json:"type2"`
	SpeciesID int32   `json:"species_id"`
}

func (q *Queries) GetPokemonLearnableAbility(ctx context.Context, abilityID int32) ([]GetPokemonLearnableAbilityRow, error) {
	rows, err := q.db.Query(ctx, getPokemonLearnableAbility, abilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPokemonLearnableAbilityRow
	for rows.Next() {
		var i GetPokemonLearnableAbilityRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gen,
			&i.Type1,
			&i.Type2,
			&i.SpeciesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
