// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Ptype string

const (
	PtypeFire     Ptype = "fire"
	PtypeWater    Ptype = "water"
	PtypeGrass    Ptype = "grass"
	PtypeNormal   Ptype = "normal"
	PtypeFighting Ptype = "fighting"
	PtypeGhost    Ptype = "ghost"
	PtypeElectric Ptype = "electric"
	PtypeGround   Ptype = "ground"
	PtypeRock     Ptype = "rock"
	PtypeSteel    Ptype = "steel"
	PtypePsychic  Ptype = "psychic"
	PtypeDark     Ptype = "dark"
	PtypeBug      Ptype = "bug"
	PtypeFairy    Ptype = "fairy"
	PtypeFlying   Ptype = "flying"
	PtypePoison   Ptype = "poison"
	PtypeIce      Ptype = "ice"
	PtypeDragon   Ptype = "dragon"
	PtypeStellar  Ptype = "stellar"
)

func (e *Ptype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Ptype(s)
	case string:
		*e = Ptype(s)
	default:
		return fmt.Errorf("unsupported scan type for Ptype: %T", src)
	}
	return nil
}

type NullPtype struct {
	Ptype Ptype `json:"ptype"`
	Valid bool  `json:"valid"` // Valid is true if Ptype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPtype) Scan(value interface{}) error {
	if value == nil {
		ns.Ptype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Ptype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPtype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Ptype), nil
}

type Pokemon struct {
	ID         int32          `json:"id"`
	Name       string         `json:"name"`
	Gen        interface{}    `json:"gen"`
	Type1      Ptype          `json:"type1"`
	Type2      NullPtype      `json:"type2"`
	Weight     pgtype.Numeric `json:"weight"`
	Height     pgtype.Numeric `json:"height"`
	GenderRate int32          `json:"gender_rate"`
	Hp         interface{}    `json:"hp"`
	Atk        interface{}    `json:"atk"`
	Def        interface{}    `json:"def"`
	Spatk      interface{}    `json:"spatk"`
	Spdef      interface{}    `json:"spdef"`
	Speed      interface{}    `json:"speed"`
	Bst        int32          `json:"bst"`
	DexEntries [][]byte       `json:"dex_entries"`
	SpeciesID  int32          `json:"species_id"`
	Forms      []string       `json:"forms"`
}
