// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
)

type Dex string

const (
	DexNational         Dex = "national"
	DexKanto            Dex = "kanto"
	DexOriginalJohto    Dex = "original-johto"
	DexHoenn            Dex = "hoenn"
	DexOriginalSinnoh   Dex = "original-sinnoh"
	DexExtendedSinnoh   Dex = "extended-sinnoh"
	DexUpdatedJohto     Dex = "updated-johto"
	DexOriginalUnova    Dex = "original-unova"
	DexUpdatedUnova     Dex = "updated-unova"
	DexKalosCentral     Dex = "kalos-central"
	DexKalosCoastal     Dex = "kalos-coastal"
	DexKalosMountain    Dex = "kalos-mountain"
	DexUpdatedHoenn     Dex = "updated-hoenn"
	DexOriginalAlola    Dex = "original-alola"
	DexOriginalMelemele Dex = "original-melemele"
	DexOriginalAkala    Dex = "original-akala"
	DexOriginalUlaula   Dex = "original-ulaula"
	DexOriginalPoni     Dex = "original-poni"
	DexUpdatedAlola     Dex = "updated-alola"
	DexUpdatedMelemele  Dex = "updated-melemele"
	DexUpdatedAkala     Dex = "updated-akala"
	DexUpdatedUlaula    Dex = "updated-ulaula"
	DexUpdatedPoni      Dex = "updated-poni"
	DexLetsgoKanto      Dex = "letsgo-kanto"
	DexGalar            Dex = "galar"
	DexIsleOfArmor      Dex = "isle-of-armor"
	DexCrownTundra      Dex = "crown-tundra"
	DexHisui            Dex = "hisui"
	DexPaldea           Dex = "paldea"
	DexKitakami         Dex = "kitakami"
	DexBlueberry        Dex = "blueberry"
)

func (e *Dex) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Dex(s)
	case string:
		*e = Dex(s)
	default:
		return fmt.Errorf("unsupported scan type for Dex: %T", src)
	}
	return nil
}

type NullDex struct {
	Dex   Dex  `json:"dex"`
	Valid bool `json:"valid"` // Valid is true if Dex is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDex) Scan(value interface{}) error {
	if value == nil {
		ns.Dex, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Dex.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDex) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Dex), nil
}

type Game string

const (
	GameRed              Game = "red"
	GameBlue             Game = "blue"
	GameYellow           Game = "yellow"
	GameGold             Game = "gold"
	GameSilver           Game = "silver"
	GameCrystal          Game = "crystal"
	GameRuby             Game = "ruby"
	GameSapphire         Game = "sapphire"
	GameEmerald          Game = "emerald"
	GameFirered          Game = "firered"
	GameLeafgreen        Game = "leafgreen"
	GameDiamond          Game = "diamond"
	GamePearl            Game = "pearl"
	GamePlatinum         Game = "platinum"
	GameHeartgold        Game = "heartgold"
	GameSoulsilver       Game = "soulsilver"
	GameBlack            Game = "black"
	GameWhite            Game = "white"
	GameBlack2           Game = "black-2"
	GameWhite2           Game = "white-2"
	GameX                Game = "x"
	GameY                Game = "y"
	GameOmegaRuby        Game = "omega-ruby"
	GameAlphaSapphire    Game = "alpha-sapphire"
	GameSun              Game = "sun"
	GameMoon             Game = "moon"
	GameUltraSun         Game = "ultra-sun"
	GameUltraMoon        Game = "ultra-moon"
	GameLetsGoPikachu    Game = "lets-go-pikachu"
	GameLetsGoEevee      Game = "lets-go-eevee"
	GameSword            Game = "sword"
	GameShield           Game = "shield"
	GameBrilliantDiamond Game = "brilliant-diamond"
	GameShiningPearl     Game = "shining-pearl"
	GameLegendsArceus    Game = "legends-arceus"
	GameScarlet          Game = "scarlet"
	GameViolet           Game = "violet"
)

func (e *Game) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Game(s)
	case string:
		*e = Game(s)
	default:
		return fmt.Errorf("unsupported scan type for Game: %T", src)
	}
	return nil
}

type NullGame struct {
	Game  Game `json:"game"`
	Valid bool `json:"valid"` // Valid is true if Game is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGame) Scan(value interface{}) error {
	if value == nil {
		ns.Game, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Game.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGame) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Game), nil
}

type Group string

const (
	GroupRedBlue                         Group = "red-blue"
	GroupYellow                          Group = "yellow"
	GroupGoldSilver                      Group = "gold-silver"
	GroupCrystal                         Group = "crystal"
	GroupRubySapphire                    Group = "ruby-sapphire"
	GroupEmerald                         Group = "emerald"
	GroupFireredLeafgreen                Group = "firered-leafgreen"
	GroupDiamondPearl                    Group = "diamond-pearl"
	GroupPlatinum                        Group = "platinum"
	GroupHeartgoldSoulsilver             Group = "heartgold-soulsilver"
	GroupBlackWhite                      Group = "black-white"
	GroupBlack2White2                    Group = "black-2-white-2"
	GroupXY                              Group = "x-y"
	GroupOmegaRubyAlphaSapphire          Group = "omega-ruby-alpha-sapphire"
	GroupSunMoon                         Group = "sun-moon"
	GroupUltraSunUltraMoon               Group = "ultra-sun-ultra-moon"
	GroupLetsGoPikachuLetsGoEevee        Group = "lets-go-pikachu-lets-go-eevee"
	GroupSwordShield                     Group = "sword-shield"
	GroupBrilliantDiamondAndShiningPearl Group = "brilliant-diamond-and-shining-pearl"
	GroupLegendsArceus                   Group = "legends-arceus"
	GroupScarletViolet                   Group = "scarlet-violet"
)

func (e *Group) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Group(s)
	case string:
		*e = Group(s)
	default:
		return fmt.Errorf("unsupported scan type for Group: %T", src)
	}
	return nil
}

type NullGroup struct {
	Group Group `json:"group"`
	Valid bool  `json:"valid"` // Valid is true if Group is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroup) Scan(value interface{}) error {
	if value == nil {
		ns.Group, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Group.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroup) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Group), nil
}

type Learnmethod string

const (
	LearnmethodLevelUp      Learnmethod = "level-up"
	LearnmethodEgg          Learnmethod = "egg"
	LearnmethodTutor        Learnmethod = "tutor"
	LearnmethodMachine      Learnmethod = "machine"
	LearnmethodLightBallEgg Learnmethod = "light-ball-egg"
	LearnmethodFormChange   Learnmethod = "form-change"
	LearnmethodZygardeCube  Learnmethod = "zygarde-cube"
)

func (e *Learnmethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Learnmethod(s)
	case string:
		*e = Learnmethod(s)
	default:
		return fmt.Errorf("unsupported scan type for Learnmethod: %T", src)
	}
	return nil
}

type NullLearnmethod struct {
	Learnmethod Learnmethod `json:"learnmethod"`
	Valid       bool        `json:"valid"` // Valid is true if Learnmethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLearnmethod) Scan(value interface{}) error {
	if value == nil {
		ns.Learnmethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Learnmethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLearnmethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Learnmethod), nil
}

type Mclass string

const (
	MclassPhysical Mclass = "physical"
	MclassSpecial  Mclass = "special"
	MclassStatus   Mclass = "status"
)

func (e *Mclass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Mclass(s)
	case string:
		*e = Mclass(s)
	default:
		return fmt.Errorf("unsupported scan type for Mclass: %T", src)
	}
	return nil
}

type NullMclass struct {
	Mclass Mclass `json:"mclass"`
	Valid  bool   `json:"valid"` // Valid is true if Mclass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMclass) Scan(value interface{}) error {
	if value == nil {
		ns.Mclass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Mclass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMclass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Mclass), nil
}

type Ptype string

const (
	PtypeFire     Ptype = "fire"
	PtypeWater    Ptype = "water"
	PtypeGrass    Ptype = "grass"
	PtypeNormal   Ptype = "normal"
	PtypeFighting Ptype = "fighting"
	PtypeGhost    Ptype = "ghost"
	PtypeElectric Ptype = "electric"
	PtypeGround   Ptype = "ground"
	PtypeRock     Ptype = "rock"
	PtypeSteel    Ptype = "steel"
	PtypePsychic  Ptype = "psychic"
	PtypeDark     Ptype = "dark"
	PtypeBug      Ptype = "bug"
	PtypeFairy    Ptype = "fairy"
	PtypeFlying   Ptype = "flying"
	PtypePoison   Ptype = "poison"
	PtypeIce      Ptype = "ice"
	PtypeDragon   Ptype = "dragon"
	PtypeStellar  Ptype = "stellar"
)

func (e *Ptype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Ptype(s)
	case string:
		*e = Ptype(s)
	default:
		return fmt.Errorf("unsupported scan type for Ptype: %T", src)
	}
	return nil
}

type NullPtype struct {
	Ptype Ptype `json:"ptype"`
	Valid bool  `json:"valid"` // Valid is true if Ptype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPtype) Scan(value interface{}) error {
	if value == nil {
		ns.Ptype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Ptype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPtype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Ptype), nil
}

type Region string

const (
	RegionAlola  Region = "alola"
	RegionGalar  Region = "galar"
	RegionHisui  Region = "hisui"
	RegionPaldea Region = "paldea"
)

func (e *Region) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Region(s)
	case string:
		*e = Region(s)
	default:
		return fmt.Errorf("unsupported scan type for Region: %T", src)
	}
	return nil
}

type NullRegion struct {
	Region Region `json:"region"`
	Valid  bool   `json:"valid"` // Valid is true if Region is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegion) Scan(value interface{}) error {
	if value == nil {
		ns.Region, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Region.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Region), nil
}

type Ability struct {
	ID     int32   `json:"id"`
	Name   string  `json:"name"`
	Gen    int32   `json:"gen"`
	Effect *string `json:"effect"`
}

type Abilitydescription struct {
	AbilityID int32  `json:"ability_id"`
	Version   string `json:"version"`
	Text      string `json:"text"`
}

type Abilitydetail struct {
	PokemonID int32  `json:"pokemon_id"`
	AbilityID int32  `json:"ability_id"`
	Hidden    bool   `json:"hidden"`
	Gen       *int32 `json:"gen"`
}

type Dexnumber struct {
	SpeciesID      int32   `json:"species_id"`
	Name           string  `json:"name"`
	Num            int32   `json:"num"`
	DefaultVariate int32   `json:"default_variate"`
	AltVariates    []int32 `json:"alt_variates"`
}

type Evolution struct {
	ChainID     int32    `json:"chain_id"`
	ID          int32    `json:"id"`
	FromPokemon int32    `json:"from_pokemon"`
	FromDisplay string   `json:"from_display"`
	ToPokemon   int32    `json:"to_pokemon"`
	ToDisplay   string   `json:"to_display"`
	Details     []string `json:"details"`
	Region      *string  `json:"region"`
	AltForm     int32    `json:"alt_form"`
	NextEvo     []int32  `json:"next_evo"`
	PrevEvo     []int32  `json:"prev_evo"`
}

type Evolutionpeek struct {
	ChainID   int32 `json:"chain_id"`
	PokemonID int32 `json:"pokemon_id"`
}

type Move struct {
	ID       int32   `json:"id"`
	Name     string  `json:"name"`
	Gen      int32   `json:"gen"`
	Type     string  `json:"type"`
	Class    string  `json:"class"`
	Power    *int32  `json:"power"`
	Accuracy *int32  `json:"accuracy"`
	Pp       *int32  `json:"pp"`
	Effect   *string `json:"effect"`
}

type Movedescription struct {
	MoveID  int32  `json:"move_id"`
	Version string `json:"version"`
	Text    string `json:"text"`
}

type Movedetail struct {
	PokemonID    int32   `json:"pokemon_id"`
	MoveID       int32   `json:"move_id"`
	Method       string  `json:"method"`
	LevelLearned int32   `json:"level_learned"`
	Version      *string `json:"version"`
}

type Pastmovevalue struct {
	ID            int32    `json:"id"`
	Power         *int32   `json:"power"`
	Accuracy      *int32   `json:"accuracy"`
	Pp            *int32   `json:"pp"`
	VersionGroups []string `json:"version_groups"`
}

type Pasttype struct {
	PokemonID int32   `json:"pokemon_id"`
	Type1     string  `json:"type1"`
	Type2     *string `json:"type2"`
	Gen       int32   `json:"gen"`
}

type Pokemon struct {
	ID         int32    `json:"id"`
	Name       string   `json:"name"`
	Gen        int32    `json:"gen"`
	Type1      string   `json:"type1"`
	Type2      *string  `json:"type2"`
	Weight     float64  `json:"weight"`
	Height     float64  `json:"height"`
	GenderRate int32    `json:"gender_rate"`
	Hp         int32    `json:"hp"`
	Atk        int32    `json:"atk"`
	Def        int32    `json:"def"`
	Spatk      int32    `json:"spatk"`
	Spdef      int32    `json:"spdef"`
	Speed      int32    `json:"speed"`
	Bst        int32    `json:"bst"`
	SpeciesID  int32    `json:"species_id"`
	Forms      []string `json:"forms"`
}

type Pokemondescription struct {
	PokemonID int32  `json:"pokemon_id"`
	Version   string `json:"version"`
	Text      string `json:"text"`
}

type Species struct {
	ID   int32   `json:"id"`
	Name *string `json:"name"`
}

type VgGame struct {
	Vg   string `json:"vg"`
	Game string `json:"game"`
}
