// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moves.sql

package store

import (
	"context"
)

const getMove = `-- name: GetMove :one
SELECT id, name, type, class, power, accuracy, pp, gen, effect
FROM move 
WHERE id = $1
`

type GetMoveRow struct {
	ID       int32   `json:"id"`
	Name     string  `json:"name"`
	Type     string  `json:"type"`
	Class    string  `json:"class"`
	Power    *int32  `json:"power"`
	Accuracy *int32  `json:"accuracy"`
	Pp       *int32  `json:"pp"`
	Gen      int32   `json:"gen"`
	Effect   *string `json:"effect"`
}

func (q *Queries) GetMove(ctx context.Context, id int32) (GetMoveRow, error) {
	row := q.db.QueryRow(ctx, getMove, id)
	var i GetMoveRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Class,
		&i.Power,
		&i.Accuracy,
		&i.Pp,
		&i.Gen,
		&i.Effect,
	)
	return i, err
}

const getMoveByName = `-- name: GetMoveByName :one
SELECT id, name, type, class, power, accuracy, pp, gen, effect
FROM move 
WHERE name = $1
`

type GetMoveByNameRow struct {
	ID       int32   `json:"id"`
	Name     string  `json:"name"`
	Type     string  `json:"type"`
	Class    string  `json:"class"`
	Power    *int32  `json:"power"`
	Accuracy *int32  `json:"accuracy"`
	Pp       *int32  `json:"pp"`
	Gen      int32   `json:"gen"`
	Effect   *string `json:"effect"`
}

func (q *Queries) GetMoveByName(ctx context.Context, name string) (GetMoveByNameRow, error) {
	row := q.db.QueryRow(ctx, getMoveByName, name)
	var i GetMoveByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Class,
		&i.Power,
		&i.Accuracy,
		&i.Pp,
		&i.Gen,
		&i.Effect,
	)
	return i, err
}

const getMoveDescriptions = `-- name: GetMoveDescriptions :many
SELECT array_agg(version ORDER BY version)::text[] AS games,
       text
FROM movedescriptions
WHERE move_id = $1
GROUP BY text
ORDER BY min(version)
`

type GetMoveDescriptionsRow struct {
	Games []string `json:"games"`
	Text  string   `json:"text"`
}

// Same grouping as GetPokemonDescriptionsByIDs; see the note there.
func (q *Queries) GetMoveDescriptions(ctx context.Context, moveID int32) ([]GetMoveDescriptionsRow, error) {
	rows, err := q.db.Query(ctx, getMoveDescriptions, moveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMoveDescriptionsRow
	for rows.Next() {
		var i GetMoveDescriptionsRow
		if err := rows.Scan(&i.Games, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMoves = `-- name: GetMoves :many
SELECT id, name, type, class, power, accuracy, pp, gen 
FROM move 
ORDER BY id, gen ASC
`

type GetMovesRow struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Type     string `json:"type"`
	Class    string `json:"class"`
	Power    *int32 `json:"power"`
	Accuracy *int32 `json:"accuracy"`
	Pp       *int32 `json:"pp"`
	Gen      int32  `json:"gen"`
}

func (q *Queries) GetMoves(ctx context.Context) ([]GetMovesRow, error) {
	rows, err := q.db.Query(ctx, getMoves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovesRow
	for rows.Next() {
		var i GetMovesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Class,
			&i.Power,
			&i.Accuracy,
			&i.Pp,
			&i.Gen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPastMoveValues = `-- name: GetPastMoveValues :many
SELECT id, power, accuracy, pp, version_groups
FROM pastmovevalues
WHERE id = $1
`

func (q *Queries) GetPastMoveValues(ctx context.Context, id int32) ([]Pastmovevalue, error) {
	rows, err := q.db.Query(ctx, getPastMoveValues, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pastmovevalue
	for rows.Next() {
		var i Pastmovevalue
		if err := rows.Scan(
			&i.ID,
			&i.Power,
			&i.Accuracy,
			&i.Pp,
			&i.VersionGroups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPokemonLearnableMove = `-- name: GetPokemonLearnableMove :many
SELECT DISTINCT p.species_id, p.id, p.name, p.type1, type2, md.method
FROM movedetails md
JOIN pokemon p ON p.id = md.pokemon_id
WHERE md.move_id = $1
ORDER BY p.species_id, p.id ASC
`

type GetPokemonLearnableMoveRow struct {
	SpeciesID int32   `json:"species_id"`
	ID        int32   `json:"id"`
	Name      string  `json:"name"`
	Type1     string  `json:"type1"`
	Type2     *string `json:"type2"`
	Method    string  `json:"method"`
}

func (q *Queries) GetPokemonLearnableMove(ctx context.Context, moveID int32) ([]GetPokemonLearnableMoveRow, error) {
	rows, err := q.db.Query(ctx, getPokemonLearnableMove, moveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPokemonLearnableMoveRow
	for rows.Next() {
		var i GetPokemonLearnableMoveRow
		if err := rows.Scan(
			&i.SpeciesID,
			&i.ID,
			&i.Name,
			&i.Type1,
			&i.Type2,
			&i.Method,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
