// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pokemon.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPokemon = `-- name: GetPokemon :one
SELECT id, species_id, name, gen, type1, type2, weight, height, gender_rate,
       hp, atk, def, spatk, spdef, speed, bst, forms
FROM pokemon
WHERE id = $1
`

type GetPokemonRow struct {
	ID         int32          `json:"id"`
	SpeciesID  int32          `json:"species_id"`
	Name       string         `json:"name"`
	Gen        interface{}    `json:"gen"`
	Type1      Ptype          `json:"type1"`
	Type2      NullPtype      `json:"type2"`
	Weight     pgtype.Numeric `json:"weight"`
	Height     pgtype.Numeric `json:"height"`
	GenderRate int32          `json:"gender_rate"`
	Hp         interface{}    `json:"hp"`
	Atk        interface{}    `json:"atk"`
	Def        interface{}    `json:"def"`
	Spatk      interface{}    `json:"spatk"`
	Spdef      interface{}    `json:"spdef"`
	Speed      interface{}    `json:"speed"`
	Bst        int32          `json:"bst"`
	Forms      []string       `json:"forms"`
}

func (q *Queries) GetPokemon(ctx context.Context, id int32) (GetPokemonRow, error) {
	row := q.db.QueryRow(ctx, getPokemon, id)
	var i GetPokemonRow
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.Name,
		&i.Gen,
		&i.Type1,
		&i.Type2,
		&i.Weight,
		&i.Height,
		&i.GenderRate,
		&i.Hp,
		&i.Atk,
		&i.Def,
		&i.Spatk,
		&i.Spdef,
		&i.Speed,
		&i.Bst,
		&i.Forms,
	)
	return i, err
}

const getPokemonByName = `-- name: GetPokemonByName :one
SELECT id, species_id, name, gen, type1, type2, weight, height, gender_rate,
       hp, atk, def, spatk, spdef, speed, bst, forms
FROM pokemon
WHERE name = $1
`

type GetPokemonByNameRow struct {
	ID         int32          `json:"id"`
	SpeciesID  int32          `json:"species_id"`
	Name       string         `json:"name"`
	Gen        interface{}    `json:"gen"`
	Type1      Ptype          `json:"type1"`
	Type2      NullPtype      `json:"type2"`
	Weight     pgtype.Numeric `json:"weight"`
	Height     pgtype.Numeric `json:"height"`
	GenderRate int32          `json:"gender_rate"`
	Hp         interface{}    `json:"hp"`
	Atk        interface{}    `json:"atk"`
	Def        interface{}    `json:"def"`
	Spatk      interface{}    `json:"spatk"`
	Spdef      interface{}    `json:"spdef"`
	Speed      interface{}    `json:"speed"`
	Bst        int32          `json:"bst"`
	Forms      []string       `json:"forms"`
}

func (q *Queries) GetPokemonByName(ctx context.Context, name string) (GetPokemonByNameRow, error) {
	row := q.db.QueryRow(ctx, getPokemonByName, name)
	var i GetPokemonByNameRow
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.Name,
		&i.Gen,
		&i.Type1,
		&i.Type2,
		&i.Weight,
		&i.Height,
		&i.GenderRate,
		&i.Hp,
		&i.Atk,
		&i.Def,
		&i.Spatk,
		&i.Spdef,
		&i.Speed,
		&i.Bst,
		&i.Forms,
	)
	return i, err
}

const listPokemon = `-- name: ListPokemon :many
SELECT id, species_id, name, gen, type1, type2, weight, height, gender_rate,
       hp, atk, def, spatk, spdef, speed, bst, forms
FROM pokemon
ORDER BY id
LIMIT 50
`

type ListPokemonRow struct {
	ID         int32          `json:"id"`
	SpeciesID  int32          `json:"species_id"`
	Name       string         `json:"name"`
	Gen        interface{}    `json:"gen"`
	Type1      Ptype          `json:"type1"`
	Type2      NullPtype      `json:"type2"`
	Weight     pgtype.Numeric `json:"weight"`
	Height     pgtype.Numeric `json:"height"`
	GenderRate int32          `json:"gender_rate"`
	Hp         interface{}    `json:"hp"`
	Atk        interface{}    `json:"atk"`
	Def        interface{}    `json:"def"`
	Spatk      interface{}    `json:"spatk"`
	Spdef      interface{}    `json:"spdef"`
	Speed      interface{}    `json:"speed"`
	Bst        int32          `json:"bst"`
	Forms      []string       `json:"forms"`
}

func (q *Queries) ListPokemon(ctx context.Context) ([]ListPokemonRow, error) {
	rows, err := q.db.Query(ctx, listPokemon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPokemonRow
	for rows.Next() {
		var i ListPokemonRow
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.Name,
			&i.Gen,
			&i.Type1,
			&i.Type2,
			&i.Weight,
			&i.Height,
			&i.GenderRate,
			&i.Hp,
			&i.Atk,
			&i.Def,
			&i.Spatk,
			&i.Spdef,
			&i.Speed,
			&i.Bst,
			&i.Forms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
