// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pokedex.sql

package store

import (
	"context"
)

const getCandidateAbilitiesByIDs = `-- name: GetCandidateAbilitiesByIDs :many
SELECT d.pokemon_id, a.id AS ability_id, a.name AS ability_name, a.gen AS ability_gen,
       d.hidden, d.gen AS gen_removed
FROM abilitydetails d
JOIN ability a ON a.id = d.ability_id
WHERE d.pokemon_id = ANY($1::int[])
ORDER BY d.pokemon_id, d.hidden, a.id
`

type GetCandidateAbilitiesByIDsRow struct {
	PokemonID   int32  `json:"pokemon_id"`
	AbilityID   int32  `json:"ability_id"`
	AbilityName string `json:"ability_name"`
	AbilityGen  int32  `json:"ability_gen"`
	Hidden      bool   `json:"hidden"`
	GenRemoved  *int32 `json:"gen_removed"`
}

func (q *Queries) GetCandidateAbilitiesByIDs(ctx context.Context, pokemonIds []int32) ([]GetCandidateAbilitiesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getCandidateAbilitiesByIDs, pokemonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCandidateAbilitiesByIDsRow
	for rows.Next() {
		var i GetCandidateAbilitiesByIDsRow
		if err := rows.Scan(
			&i.PokemonID,
			&i.AbilityID,
			&i.AbilityName,
			&i.AbilityGen,
			&i.Hidden,
			&i.GenRemoved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandidateMovesByIDs = `-- name: GetCandidateMovesByIDs :many
SELECT DISTINCT d.pokemon_id, d.move_id, m.name, m.type, m.class
FROM movedetails d
JOIN move m ON d.move_id = m.id
WHERE d.pokemon_id = ANY($1::int[])
ORDER BY d.pokemon_id, d.move_id
`

type GetCandidateMovesByIDsRow struct {
	PokemonID int32  `json:"pokemon_id"`
	MoveID    int32  `json:"move_id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Class     string `json:"class"`
}

func (q *Queries) GetCandidateMovesByIDs(ctx context.Context, pokemonIds []int32) ([]GetCandidateMovesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getCandidateMovesByIDs, pokemonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCandidateMovesByIDsRow
	for rows.Next() {
		var i GetCandidateMovesByIDsRow
		if err := rows.Scan(
			&i.PokemonID,
			&i.MoveID,
			&i.Name,
			&i.Type,
			&i.Class,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandidateMovesByIDsAndVersion = `-- name: GetCandidateMovesByIDsAndVersion :many
SELECT DISTINCT d.pokemon_id, d.move_id, m.name, m.type, m.class
FROM movedetails d
JOIN move m ON d.move_id = m.id
WHERE d.pokemon_id = ANY($1::int[]) AND d.version = $2
ORDER BY d.pokemon_id, d.move_id
`

type GetCandidateMovesByIDsAndVersionParams struct {
	PokemonIds []int32     `json:"pokemon_ids"`
	Version    interface{} `json:"version"`
}

type GetCandidateMovesByIDsAndVersionRow struct {
	PokemonID int32  `json:"pokemon_id"`
	MoveID    int32  `json:"move_id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Class     string `json:"class"`
}

func (q *Queries) GetCandidateMovesByIDsAndVersion(ctx context.Context, arg GetCandidateMovesByIDsAndVersionParams) ([]GetCandidateMovesByIDsAndVersionRow, error) {
	rows, err := q.db.Query(ctx, getCandidateMovesByIDsAndVersion, arg.PokemonIds, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCandidateMovesByIDsAndVersionRow
	for rows.Next() {
		var i GetCandidateMovesByIDsAndVersionRow
		if err := rows.Scan(
			&i.PokemonID,
			&i.MoveID,
			&i.Name,
			&i.Type,
			&i.Class,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDexByRegion = `-- name: GetDexByRegion :many
SELECT d.num, p.id, s.name, s.id AS species_id, p.gen,
       COALESCE(pt.type1, p.type1) AS type1,
       CASE WHEN pt.type1 IS NOT NULL THEN pt.type2 ELSE p.type2 END AS type2
FROM dexnumber d
JOIN pokemon p ON d.default_variate = p.id OR d.alt_variates @> ARRAY[p.id]
JOIN species s ON s.id = d.species_id
LEFT JOIN pasttypes pt ON p.id = pt.pokemon_id AND pt.gen >= $1
WHERE d.name = $2
ORDER BY d.num, CASE WHEN p.id = d.default_variate THEN 0 ELSE 1 END, p.id
`

type GetDexByRegionParams struct {
	Gen  int32 `json:"gen"`
	Name Dex   `json:"name"`
}

type GetDexByRegionRow struct {
	Num       int32   `json:"num"`
	ID        int32   `json:"id"`
	Name      *string `json:"name"`
	SpeciesID int32   `json:"species_id"`
	Gen       int32   `json:"gen"`
	Type1     string  `json:"type1"`
	Type2     *string `json:"type2"`
}

func (q *Queries) GetDexByRegion(ctx context.Context, arg GetDexByRegionParams) ([]GetDexByRegionRow, error) {
	rows, err := q.db.Query(ctx, getDexByRegion, arg.Gen, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDexByRegionRow
	for rows.Next() {
		var i GetDexByRegionRow
		if err := rows.Scan(
			&i.Num,
			&i.ID,
			&i.Name,
			&i.SpeciesID,
			&i.Gen,
			&i.Type1,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDexNational = `-- name: GetDexNational :many
SELECT s.id AS species_id, p.id, s.name, p.gen, p.type1, p.type2
FROM pokemon p
JOIN species s ON s.id = p.species_id
ORDER BY s.id, p.id ASC
`

type GetDexNationalRow struct {
	SpeciesID int32   `json:"species_id"`
	ID        int32   `json:"id"`
	Name      *string `json:"name"`
	Gen       int32   `json:"gen"`
	Type1     string  `json:"type1"`
	Type2     *string `json:"type2"`
}

func (q *Queries) GetDexNational(ctx context.Context) ([]GetDexNationalRow, error) {
	rows, err := q.db.Query(ctx, getDexNational)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDexNationalRow
	for rows.Next() {
		var i GetDexNationalRow
		if err := rows.Scan(
			&i.SpeciesID,
			&i.ID,
			&i.Name,
			&i.Gen,
			&i.Type1,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamCandidateByID = `-- name: GetTeamCandidateByID :one
SELECT p.id, p.name, p.gen, p.gender_rate,
       COALESCE(pt.type1, p.type1) AS type1,
       CASE WHEN pt.type1 IS NOT NULL THEN pt.type2 ELSE p.type2 END AS type2
FROM pokemon p
LEFT JOIN LATERAL (
    SELECT type1, type2
    FROM pasttypes
    WHERE pokemon_id = p.id AND gen >= $1::public.generation
    ORDER BY gen
    LIMIT 1
) pt ON TRUE
WHERE p.id = $2::int
  AND (
    EXISTS (
      SELECT 1 FROM dexnumber d
      WHERE d.name::text = ANY($3::text[])
        AND (d.default_variate = p.id OR d.alt_variates @> ARRAY[p.id])
    )
    OR EXISTS (
      SELECT 1 FROM movedetails md
      WHERE md.pokemon_id = p.id AND md.version = $4::public."group"
    )
  )
`

type GetTeamCandidateByIDParams struct {
	Gen       int32    `json:"gen"`
	PokemonID int32    `json:"pokemon_id"`
	Regions   []string `json:"regions"`
	Version   string   `json:"version"`
}

type GetTeamCandidateByIDRow struct {
	ID         int32   `json:"id"`
	Name       string  `json:"name"`
	Gen        int32   `json:"gen"`
	GenderRate int32   `json:"gender_rate"`
	Type1      string  `json:"type1"`
	Type2      *string `json:"type2"`
}

// Single candidate for a non-national version group. The EXISTS pair is the same
// membership union the list endpoint builds — in one of the version group's regional
// dexes, or learning a move in that version — so a Pokemon absent from the game
// yields no row. The lateral picks the earliest applicable past-typing record
// deterministically, which a plain LEFT JOIN could not guarantee for a :one query.
func (q *Queries) GetTeamCandidateByID(ctx context.Context, arg GetTeamCandidateByIDParams) (GetTeamCandidateByIDRow, error) {
	row := q.db.QueryRow(ctx, getTeamCandidateByID,
		arg.Gen,
		arg.PokemonID,
		arg.Regions,
		arg.Version,
	)
	var i GetTeamCandidateByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gen,
		&i.GenderRate,
		&i.Type1,
		&i.Type2,
	)
	return i, err
}

const getTeamCandidateNationalByID = `-- name: GetTeamCandidateNationalByID :one
SELECT p.id, s.name, p.gen, p.type1, p.type2, p.gender_rate
FROM pokemon p
JOIN species s ON s.id = p.species_id
WHERE p.id = $1
`

type GetTeamCandidateNationalByIDRow struct {
	ID         int32   `json:"id"`
	Name       *string `json:"name"`
	Gen        int32   `json:"gen"`
	Type1      string  `json:"type1"`
	Type2      *string `json:"type2"`
	GenderRate int32   `json:"gender_rate"`
}

// Mirrors GetTeamCandidatesNational: species name, raw types, and no membership
// check since the national list contains every Pokemon.
func (q *Queries) GetTeamCandidateNationalByID(ctx context.Context, id int32) (GetTeamCandidateNationalByIDRow, error) {
	row := q.db.QueryRow(ctx, getTeamCandidateNationalByID, id)
	var i GetTeamCandidateNationalByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gen,
		&i.Type1,
		&i.Type2,
		&i.GenderRate,
	)
	return i, err
}

const getTeamCandidatesByRegion = `-- name: GetTeamCandidatesByRegion :many
SELECT d.num, p.id, p.name, p.gen, p.gender_rate,
       COALESCE(pt.type1, p.type1) AS type1,
       CASE WHEN pt.type1 IS NOT NULL THEN pt.type2 ELSE p.type2 END AS type2
FROM dexnumber d
JOIN pokemon p ON d.default_variate = p.id OR d.alt_variates @> ARRAY[p.id]
JOIN species s ON s.id = d.species_id
LEFT JOIN pasttypes pt ON p.id = pt.pokemon_id AND pt.gen >= $1
WHERE d.name = $2
ORDER BY d.num, CASE WHEN p.id = d.default_variate THEN 0 ELSE 1 END, p.id
`

type GetTeamCandidatesByRegionParams struct {
	Gen  int32 `json:"gen"`
	Name Dex   `json:"name"`
}

type GetTeamCandidatesByRegionRow struct {
	Num        int32   `json:"num"`
	ID         int32   `json:"id"`
	Name       string  `json:"name"`
	Gen        int32   `json:"gen"`
	GenderRate int32   `json:"gender_rate"`
	Type1      string  `json:"type1"`
	Type2      *string `json:"type2"`
}

func (q *Queries) GetTeamCandidatesByRegion(ctx context.Context, arg GetTeamCandidatesByRegionParams) ([]GetTeamCandidatesByRegionRow, error) {
	rows, err := q.db.Query(ctx, getTeamCandidatesByRegion, arg.Gen, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamCandidatesByRegionRow
	for rows.Next() {
		var i GetTeamCandidatesByRegionRow
		if err := rows.Scan(
			&i.Num,
			&i.ID,
			&i.Name,
			&i.Gen,
			&i.GenderRate,
			&i.Type1,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamCandidatesNational = `-- name: GetTeamCandidatesNational :many
SELECT s.id AS num, s.id AS species_id, p.id, s.name, p.gen, p.type1, p.type2, p.gender_rate
FROM pokemon p
JOIN species s ON s.id = p.species_id
ORDER BY s.id, p.id ASC
`

type GetTeamCandidatesNationalRow struct {
	Num        int32   `json:"num"`
	SpeciesID  int32   `json:"species_id"`
	ID         int32   `json:"id"`
	Name       *string `json:"name"`
	Gen        int32   `json:"gen"`
	Type1      string  `json:"type1"`
	Type2      *string `json:"type2"`
	GenderRate int32   `json:"gender_rate"`
}

func (q *Queries) GetTeamCandidatesNational(ctx context.Context) ([]GetTeamCandidatesNationalRow, error) {
	rows, err := q.db.Query(ctx, getTeamCandidatesNational)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamCandidatesNationalRow
	for rows.Next() {
		var i GetTeamCandidatesNationalRow
		if err := rows.Scan(
			&i.Num,
			&i.SpeciesID,
			&i.ID,
			&i.Name,
			&i.Gen,
			&i.Type1,
			&i.Type2,
			&i.GenderRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamCandidatesNationalByVersionGroup = `-- name: GetTeamCandidatesNationalByVersionGroup :many
SELECT DISTINCT p.id, p.name, p.gen, p.gender_rate, p.species_id,
       COALESCE(pt.type1, p.type1) AS type1,
       CASE WHEN pt.type1 IS NOT NULL THEN pt.type2 ELSE p.type2 END AS type2
FROM pokemon p
JOIN movedetails md ON p.id = md.pokemon_id
LEFT JOIN pasttypes pt ON p.id = pt.pokemon_id AND pt.gen >= $1
WHERE md.version = $2
ORDER BY p.species_id, p.id
`

type GetTeamCandidatesNationalByVersionGroupParams struct {
	Gen     int32       `json:"gen"`
	Version interface{} `json:"version"`
}

type GetTeamCandidatesNationalByVersionGroupRow struct {
	ID         int32   `json:"id"`
	Name       string  `json:"name"`
	Gen        int32   `json:"gen"`
	GenderRate int32   `json:"gender_rate"`
	SpeciesID  int32   `json:"species_id"`
	Type1      string  `json:"type1"`
	Type2      *string `json:"type2"`
}

func (q *Queries) GetTeamCandidatesNationalByVersionGroup(ctx context.Context, arg GetTeamCandidatesNationalByVersionGroupParams) ([]GetTeamCandidatesNationalByVersionGroupRow, error) {
	rows, err := q.db.Query(ctx, getTeamCandidatesNationalByVersionGroup, arg.Gen, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamCandidatesNationalByVersionGroupRow
	for rows.Next() {
		var i GetTeamCandidatesNationalByVersionGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gen,
			&i.GenderRate,
			&i.SpeciesID,
			&i.Type1,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
