// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pokedex.sql

package store

import (
	"context"
)

const getDexByRegion = `-- name: GetDexByRegion :many
SELECT d.num, p.id, s.name, s.id AS species_id, p.gen,
       COALESCE(pt.type1, p.type1) AS type1,
       CASE WHEN pt.type1 IS NOT NULL THEN COALESCE(pt.type2::text, '') ELSE COALESCE(p.type2::text, '') END AS type2
FROM dexnumber d
JOIN pokemon p ON d.default_variate = p.id OR d.alt_variates @> ARRAY[p.id]
JOIN species s ON s.id = d.species_id
LEFT JOIN pasttypes pt ON p.id = pt.pokemon_id AND pt.gen >= $1
WHERE d.name = $2
ORDER BY d.num, CASE WHEN p.id = d.default_variate THEN 0 ELSE 1 END
`

type GetDexByRegionParams struct {
	Gen  int32 `json:"gen"`
	Name Dex   `json:"name"`
}

type GetDexByRegionRow struct {
	Num       int32   `json:"num"`
	ID        int32   `json:"id"`
	Name      *string `json:"name"`
	SpeciesID int32   `json:"species_id"`
	Gen       int32   `json:"gen"`
	Type1     string  `json:"type1"`
	Type2     *string `json:"type2"`
}

func (q *Queries) GetDexByRegion(ctx context.Context, arg GetDexByRegionParams) ([]GetDexByRegionRow, error) {
	rows, err := q.db.Query(ctx, getDexByRegion, arg.Gen, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDexByRegionRow
	for rows.Next() {
		var i GetDexByRegionRow
		if err := rows.Scan(
			&i.Num,
			&i.ID,
			&i.Name,
			&i.SpeciesID,
			&i.Gen,
			&i.Type1,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDexNational = `-- name: GetDexNational :many
SELECT s.id AS species_id, p.id, s.name, p.gen, p.type1, COALESCE(p.type2::text, '') AS type2
FROM pokemon p
JOIN species s ON s.id = p.species_id
ORDER BY s.id, p.id ASC
`

type GetDexNationalRow struct {
	SpeciesID int32   `json:"species_id"`
	ID        int32   `json:"id"`
	Name      *string `json:"name"`
	Gen       int32   `json:"gen"`
	Type1     string  `json:"type1"`
	Type2     *string `json:"type2"`
}

func (q *Queries) GetDexNational(ctx context.Context) ([]GetDexNationalRow, error) {
	rows, err := q.db.Query(ctx, getDexNational)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDexNationalRow
	for rows.Next() {
		var i GetDexNationalRow
		if err := rows.Scan(
			&i.SpeciesID,
			&i.ID,
			&i.Name,
			&i.Gen,
			&i.Type1,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamCandidatesByRegion = `-- name: GetTeamCandidatesByRegion :many
SELECT d.num, p.id, p.name, p.gen, p.gender_rate,
       COALESCE(pt.type1, p.type1) AS type1,
       CASE WHEN pt.type1 IS NOT NULL THEN COALESCE(pt.type2::text, '') ELSE COALESCE(p.type2::text, '') END AS type2
FROM dexnumber d
JOIN pokemon p ON d.default_variate = p.id OR d.alt_variates @> ARRAY[p.id]
JOIN species s ON s.id = d.species_id
LEFT JOIN pasttypes pt ON p.id = pt.pokemon_id AND pt.gen >= $1
WHERE d.name = $2
ORDER BY d.num, CASE WHEN p.id = d.default_variate THEN 0 ELSE 1 END
`

type GetTeamCandidatesByRegionParams struct {
	Gen  int32 `json:"gen"`
	Name Dex   `json:"name"`
}

type GetTeamCandidatesByRegionRow struct {
	Num        int32   `json:"num"`
	ID         int32   `json:"id"`
	Name       string  `json:"name"`
	Gen        int32   `json:"gen"`
	GenderRate int32   `json:"gender_rate"`
	Type1      string  `json:"type1"`
	Type2      *string `json:"type2"`
}

func (q *Queries) GetTeamCandidatesByRegion(ctx context.Context, arg GetTeamCandidatesByRegionParams) ([]GetTeamCandidatesByRegionRow, error) {
	rows, err := q.db.Query(ctx, getTeamCandidatesByRegion, arg.Gen, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamCandidatesByRegionRow
	for rows.Next() {
		var i GetTeamCandidatesByRegionRow
		if err := rows.Scan(
			&i.Num,
			&i.ID,
			&i.Name,
			&i.Gen,
			&i.GenderRate,
			&i.Type1,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamCandidatesNational = `-- name: GetTeamCandidatesNational :many
SELECT s.id AS num, s.id AS species_id, p.id, s.name, p.gen, p.type1, COALESCE(p.type2::text, '') AS type2
FROM pokemon p
JOIN species s ON s.id = p.species_id
ORDER BY s.id, p.id ASC
`

type GetTeamCandidatesNationalRow struct {
	Num       int32   `json:"num"`
	SpeciesID int32   `json:"species_id"`
	ID        int32   `json:"id"`
	Name      *string `json:"name"`
	Gen       int32   `json:"gen"`
	Type1     string  `json:"type1"`
	Type2     *string `json:"type2"`
}

func (q *Queries) GetTeamCandidatesNational(ctx context.Context) ([]GetTeamCandidatesNationalRow, error) {
	rows, err := q.db.Query(ctx, getTeamCandidatesNational)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamCandidatesNationalRow
	for rows.Next() {
		var i GetTeamCandidatesNationalRow
		if err := rows.Scan(
			&i.Num,
			&i.SpeciesID,
			&i.ID,
			&i.Name,
			&i.Gen,
			&i.Type1,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamCandidatesNationalByVersionGroup = `-- name: GetTeamCandidatesNationalByVersionGroup :many
SELECT DISTINCT p.id, p.name, p.gen, p.gender_rate, p.species_id,
       COALESCE(pt.type1, p.type1) AS type1,
       CASE WHEN pt.type1 IS NOT NULL THEN COALESCE(pt.type2::text, '') ELSE COALESCE(p.type2::text, '') END AS type2
FROM pokemon p
JOIN movedetails md ON p.id = md.pokemon_id
LEFT JOIN pasttypes pt ON p.id = pt.pokemon_id AND pt.gen >= $1
WHERE md.version = $2
ORDER BY p.species_id, p.id
`

type GetTeamCandidatesNationalByVersionGroupParams struct {
	Gen     int32       `json:"gen"`
	Version interface{} `json:"version"`
}

type GetTeamCandidatesNationalByVersionGroupRow struct {
	ID         int32   `json:"id"`
	Name       string  `json:"name"`
	Gen        int32   `json:"gen"`
	GenderRate int32   `json:"gender_rate"`
	SpeciesID  int32   `json:"species_id"`
	Type1      string  `json:"type1"`
	Type2      *string `json:"type2"`
}

func (q *Queries) GetTeamCandidatesNationalByVersionGroup(ctx context.Context, arg GetTeamCandidatesNationalByVersionGroupParams) ([]GetTeamCandidatesNationalByVersionGroupRow, error) {
	rows, err := q.db.Query(ctx, getTeamCandidatesNationalByVersionGroup, arg.Gen, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamCandidatesNationalByVersionGroupRow
	for rows.Next() {
		var i GetTeamCandidatesNationalByVersionGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gen,
			&i.GenderRate,
			&i.SpeciesID,
			&i.Type1,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
