// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pokemon.sql

package store

import (
	"context"
)

const getDexNumbersByIDs = `-- name: GetDexNumbersByIDs :many
SELECT ids.pokemon_id, d.species_id, d.name, d.num, d.default_variate, d.alt_variates
FROM unnest($1::int[]) AS ids(pokemon_id)
JOIN dexnumber d ON d.default_variate = ids.pokemon_id OR d.alt_variates @> ARRAY[ids.pokemon_id]
ORDER BY ids.pokemon_id, d.name
`

type GetDexNumbersByIDsRow struct {
	PokemonID      *int32  `json:"pokemon_id"`
	SpeciesID      int32   `json:"species_id"`
	Name           string  `json:"name"`
	Num            int32   `json:"num"`
	DefaultVariate int32   `json:"default_variate"`
	AltVariates    []int32 `json:"alt_variates"`
}

func (q *Queries) GetDexNumbersByIDs(ctx context.Context, pokemonIds []int32) ([]GetDexNumbersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getDexNumbersByIDs, pokemonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDexNumbersByIDsRow
	for rows.Next() {
		var i GetDexNumbersByIDsRow
		if err := rows.Scan(
			&i.PokemonID,
			&i.SpeciesID,
			&i.Name,
			&i.Num,
			&i.DefaultVariate,
			&i.AltVariates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvolutionChainByIDs = `-- name: GetEvolutionChainByIDs :many
SELECT ids.pokemon_id, e.chain_id, e.id, e.from_pokemon, e.from_display, e.to_pokemon,
       e.to_display, e.details, e.region, e.alt_form, e.next_evo, e.prev_evo
FROM unnest($1::int[]) AS ids(pokemon_id)
CROSS JOIN LATERAL get_evolution_chain_by_id(ids.pokemon_id) e
ORDER BY ids.pokemon_id, e.id
`

type GetEvolutionChainByIDsRow struct {
	PokemonID   *int32   `json:"pokemon_id"`
	ChainID     int32    `json:"chain_id"`
	ID          int32    `json:"id"`
	FromPokemon int32    `json:"from_pokemon"`
	FromDisplay string   `json:"from_display"`
	ToPokemon   int32    `json:"to_pokemon"`
	ToDisplay   string   `json:"to_display"`
	Details     []string `json:"details"`
	Region      *string  `json:"region"`
	AltForm     int32    `json:"alt_form"`
	NextEvo     []int32  `json:"next_evo"`
	PrevEvo     []int32  `json:"prev_evo"`
}

func (q *Queries) GetEvolutionChainByIDs(ctx context.Context, pokemonIds []int32) ([]GetEvolutionChainByIDsRow, error) {
	rows, err := q.db.Query(ctx, getEvolutionChainByIDs, pokemonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEvolutionChainByIDsRow
	for rows.Next() {
		var i GetEvolutionChainByIDsRow
		if err := rows.Scan(
			&i.PokemonID,
			&i.ChainID,
			&i.ID,
			&i.FromPokemon,
			&i.FromDisplay,
			&i.ToPokemon,
			&i.ToDisplay,
			&i.Details,
			&i.Region,
			&i.AltForm,
			&i.NextEvo,
			&i.PrevEvo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPokemon = `-- name: GetPokemon :one
SELECT id, species_id, name, gen, type1, type2, weight, height, gender_rate,
       hp, atk, def, spatk, spdef, speed, bst, forms
FROM pokemon
WHERE id = $1
`

type GetPokemonRow struct {
	ID         int32    `json:"id"`
	SpeciesID  int32    `json:"species_id"`
	Name       string   `json:"name"`
	Gen        int32    `json:"gen"`
	Type1      string   `json:"type1"`
	Type2      *string  `json:"type2"`
	Weight     float64  `json:"weight"`
	Height     float64  `json:"height"`
	GenderRate int32    `json:"gender_rate"`
	Hp         int32    `json:"hp"`
	Atk        int32    `json:"atk"`
	Def        int32    `json:"def"`
	Spatk      int32    `json:"spatk"`
	Spdef      int32    `json:"spdef"`
	Speed      int32    `json:"speed"`
	Bst        int32    `json:"bst"`
	Forms      []string `json:"forms"`
}

func (q *Queries) GetPokemon(ctx context.Context, id int32) (GetPokemonRow, error) {
	row := q.db.QueryRow(ctx, getPokemon, id)
	var i GetPokemonRow
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.Name,
		&i.Gen,
		&i.Type1,
		&i.Type2,
		&i.Weight,
		&i.Height,
		&i.GenderRate,
		&i.Hp,
		&i.Atk,
		&i.Def,
		&i.Spatk,
		&i.Spdef,
		&i.Speed,
		&i.Bst,
		&i.Forms,
	)
	return i, err
}

const getPokemonAbilitiesByIDs = `-- name: GetPokemonAbilitiesByIDs :many
SELECT d.pokemon_id, a.id AS ability_id, a.name AS ability_name, a.gen AS ability_gen,
       d.hidden, d.gen AS gen_removed
FROM abilitydetails d
JOIN ability a ON a.id = d.ability_id
WHERE d.pokemon_id = ANY($1::int[])
ORDER BY d.pokemon_id, d.hidden, a.id
`

type GetPokemonAbilitiesByIDsRow struct {
	PokemonID   int32  `json:"pokemon_id"`
	AbilityID   int32  `json:"ability_id"`
	AbilityName string `json:"ability_name"`
	AbilityGen  int32  `json:"ability_gen"`
	Hidden      bool   `json:"hidden"`
	GenRemoved  *int32 `json:"gen_removed"`
}

func (q *Queries) GetPokemonAbilitiesByIDs(ctx context.Context, pokemonIds []int32) ([]GetPokemonAbilitiesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getPokemonAbilitiesByIDs, pokemonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPokemonAbilitiesByIDsRow
	for rows.Next() {
		var i GetPokemonAbilitiesByIDsRow
		if err := rows.Scan(
			&i.PokemonID,
			&i.AbilityID,
			&i.AbilityName,
			&i.AbilityGen,
			&i.Hidden,
			&i.GenRemoved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPokemonByName = `-- name: GetPokemonByName :one
SELECT id, species_id, name, gen, type1, type2, weight, height, gender_rate,
       hp, atk, def, spatk, spdef, speed, bst, forms
FROM pokemon
WHERE name = $1
`

type GetPokemonByNameRow struct {
	ID         int32    `json:"id"`
	SpeciesID  int32    `json:"species_id"`
	Name       string   `json:"name"`
	Gen        int32    `json:"gen"`
	Type1      string   `json:"type1"`
	Type2      *string  `json:"type2"`
	Weight     float64  `json:"weight"`
	Height     float64  `json:"height"`
	GenderRate int32    `json:"gender_rate"`
	Hp         int32    `json:"hp"`
	Atk        int32    `json:"atk"`
	Def        int32    `json:"def"`
	Spatk      int32    `json:"spatk"`
	Spdef      int32    `json:"spdef"`
	Speed      int32    `json:"speed"`
	Bst        int32    `json:"bst"`
	Forms      []string `json:"forms"`
}

func (q *Queries) GetPokemonByName(ctx context.Context, name string) (GetPokemonByNameRow, error) {
	row := q.db.QueryRow(ctx, getPokemonByName, name)
	var i GetPokemonByNameRow
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.Name,
		&i.Gen,
		&i.Type1,
		&i.Type2,
		&i.Weight,
		&i.Height,
		&i.GenderRate,
		&i.Hp,
		&i.Atk,
		&i.Def,
		&i.Spatk,
		&i.Spdef,
		&i.Speed,
		&i.Bst,
		&i.Forms,
	)
	return i, err
}

const getPokemonDescriptionsByIDs = `-- name: GetPokemonDescriptionsByIDs :many
SELECT pokemon_id, version, text
FROM pokemondescriptions
WHERE pokemon_id = ANY($1::int[])
ORDER BY pokemon_id, version
`

// One row per game. `version` is the public.game enum, declared in release
// order, so ORDER BY sorts chronologically with no Go-side sort needed.
func (q *Queries) GetPokemonDescriptionsByIDs(ctx context.Context, pokemonIds []int32) ([]Pokemondescription, error) {
	rows, err := q.db.Query(ctx, getPokemonDescriptionsByIDs, pokemonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pokemondescription
	for rows.Next() {
		var i Pokemondescription
		if err := rows.Scan(&i.PokemonID, &i.Version, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPokemonMovesByIDs = `-- name: GetPokemonMovesByIDs :many
SELECT
    d.pokemon_id, d.move_id, m.name, m.type, d.level_learned, d.method,
    d.version, m.class,
    COALESCE(pmv.power, m.power) AS power,
    COALESCE(pmv.accuracy, m.accuracy) AS accuracy,
    COALESCE(pmv.pp, m.pp) AS pp
FROM movedetails d
JOIN move m ON d.move_id = m.id
LEFT JOIN pastmovevalues pmv ON d.move_id = pmv.id AND pmv.version_groups @> ARRAY[d.version]
WHERE d.pokemon_id = ANY($1::int[])
ORDER BY d.pokemon_id, d.version, d.method, d.level_learned, d.move_id
`

type GetPokemonMovesByIDsRow struct {
	PokemonID    int32   `json:"pokemon_id"`
	MoveID       int32   `json:"move_id"`
	Name         string  `json:"name"`
	Type         string  `json:"type"`
	LevelLearned int32   `json:"level_learned"`
	Method       string  `json:"method"`
	Version      *string `json:"version"`
	Class        string  `json:"class"`
	Power        *int32  `json:"power"`
	Accuracy     *int32  `json:"accuracy"`
	Pp           *int32  `json:"pp"`
}

func (q *Queries) GetPokemonMovesByIDs(ctx context.Context, pokemonIds []int32) ([]GetPokemonMovesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getPokemonMovesByIDs, pokemonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPokemonMovesByIDsRow
	for rows.Next() {
		var i GetPokemonMovesByIDsRow
		if err := rows.Scan(
			&i.PokemonID,
			&i.MoveID,
			&i.Name,
			&i.Type,
			&i.LevelLearned,
			&i.Method,
			&i.Version,
			&i.Class,
			&i.Power,
			&i.Accuracy,
			&i.Pp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
