// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: species.sql

package store

import (
	"context"
)

const getPokemonIdsBySpeciesID = `-- name: GetPokemonIdsBySpeciesID :many
SELECT id FROM pokemon WHERE species_id = $1 ORDER BY id ASC
`

func (q *Queries) GetPokemonIdsBySpeciesID(ctx context.Context, speciesID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getPokemonIdsBySpeciesID, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpeciesByID = `-- name: GetSpeciesByID :one
SELECT id, name FROM species WHERE id = $1
`

func (q *Queries) GetSpeciesByID(ctx context.Context, id int32) (Species, error) {
	row := q.db.QueryRow(ctx, getSpeciesByID, id)
	var i Species
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSpeciesByName = `-- name: GetSpeciesByName :one
SELECT id, name FROM species WHERE name = $1
`

func (q *Queries) GetSpeciesByName(ctx context.Context, name *string) (Species, error) {
	row := q.db.QueryRow(ctx, getSpeciesByName, name)
	var i Species
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSpeciesIdFromPokemon = `-- name: GetSpeciesIdFromPokemon :one
SELECT species_id FROM pokemon WHERE id = $1
`

func (q *Queries) GetSpeciesIdFromPokemon(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getSpeciesIdFromPokemon, id)
	var species_id int32
	err := row.Scan(&species_id)
	return species_id, err
}
