// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: species.sql

package store

import (
	"context"
)

const getPokemonSummariesBySpeciesID = `-- name: GetPokemonSummariesBySpeciesID :many
SELECT id, name, gen, type1, COALESCE(type2::text, '') AS type2
FROM pokemon
WHERE species_id = $1
ORDER BY id
`

type GetPokemonSummariesBySpeciesIDRow struct {
	ID    int32   `json:"id"`
	Name  string  `json:"name"`
	Gen   int32   `json:"gen"`
	Type1 string  `json:"type1"`
	Type2 *string `json:"type2"`
}

func (q *Queries) GetPokemonSummariesBySpeciesID(ctx context.Context, speciesID int32) ([]GetPokemonSummariesBySpeciesIDRow, error) {
	rows, err := q.db.Query(ctx, getPokemonSummariesBySpeciesID, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPokemonSummariesBySpeciesIDRow
	for rows.Next() {
		var i GetPokemonSummariesBySpeciesIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gen,
			&i.Type1,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpeciesByID = `-- name: GetSpeciesByID :one
SELECT id, name FROM species WHERE id = $1
`

func (q *Queries) GetSpeciesByID(ctx context.Context, id int32) (Species, error) {
	row := q.db.QueryRow(ctx, getSpeciesByID, id)
	var i Species
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSpeciesByName = `-- name: GetSpeciesByName :one
SELECT id, name FROM species WHERE name = $1
`

func (q *Queries) GetSpeciesByName(ctx context.Context, name *string) (Species, error) {
	row := q.db.QueryRow(ctx, getSpeciesByName, name)
	var i Species
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
