// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: species.sql

package store

import (
	"context"
)

const getPokemonBySpeciesID = `-- name: GetPokemonBySpeciesID :many
SELECT id, species_id, name, gen, type1, type2, weight, height, gender_rate,
       hp, atk, def, spatk, spdef, speed, bst, forms
FROM pokemon
WHERE species_id = $1
ORDER BY id
`

type GetPokemonBySpeciesIDRow struct {
	ID         int32    `json:"id"`
	SpeciesID  int32    `json:"species_id"`
	Name       string   `json:"name"`
	Gen        int32    `json:"gen"`
	Type1      string   `json:"type1"`
	Type2      *string  `json:"type2"`
	Weight     float64  `json:"weight"`
	Height     float64  `json:"height"`
	GenderRate int32    `json:"gender_rate"`
	Hp         int32    `json:"hp"`
	Atk        int32    `json:"atk"`
	Def        int32    `json:"def"`
	Spatk      int32    `json:"spatk"`
	Spdef      int32    `json:"spdef"`
	Speed      int32    `json:"speed"`
	Bst        int32    `json:"bst"`
	Forms      []string `json:"forms"`
}

func (q *Queries) GetPokemonBySpeciesID(ctx context.Context, speciesID int32) ([]GetPokemonBySpeciesIDRow, error) {
	rows, err := q.db.Query(ctx, getPokemonBySpeciesID, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPokemonBySpeciesIDRow
	for rows.Next() {
		var i GetPokemonBySpeciesIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.Name,
			&i.Gen,
			&i.Type1,
			&i.Type2,
			&i.Weight,
			&i.Height,
			&i.GenderRate,
			&i.Hp,
			&i.Atk,
			&i.Def,
			&i.Spatk,
			&i.Spdef,
			&i.Speed,
			&i.Bst,
			&i.Forms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpeciesByID = `-- name: GetSpeciesByID :one
SELECT id, name FROM species WHERE id = $1
`

func (q *Queries) GetSpeciesByID(ctx context.Context, id int32) (Species, error) {
	row := q.db.QueryRow(ctx, getSpeciesByID, id)
	var i Species
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSpeciesByName = `-- name: GetSpeciesByName :one
SELECT id, name FROM species WHERE name = $1
`

func (q *Queries) GetSpeciesByName(ctx context.Context, name *string) (Species, error) {
	row := q.db.QueryRow(ctx, getSpeciesByName, name)
	var i Species
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSpeciesIdFromPokemon = `-- name: GetSpeciesIdFromPokemon :one
SELECT species_id FROM pokemon WHERE id = $1
`

func (q *Queries) GetSpeciesIdFromPokemon(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getSpeciesIdFromPokemon, id)
	var species_id int32
	err := row.Scan(&species_id)
	return species_id, err
}
